### ISSUE TITLE
Simple log not working

### ISSUE THREAD

**Issue by mitiaptest** [miktam/loggly#4]
Hello Guys,

We have updated loggly package to latest one and following log giving error at server methods.

Logger.log("first log from meteor"); 

Exception while invoking method 'logglyLog' { stack: 'Error: Match error: Expected object, got string\n    at check (packages/check/match.js:33:1)\n    at [object Object].Meteor.methods.logglyLog (packages/miktam_loggly/logglyMeteorMethods.js:15:1)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (livedata_server.js:1698:12)\n    at livedata_server.js:708:19\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:706:40\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:704:46\n    at tryCallTwo (/home/user/.meteor/packages/promise/.0.5.1.dd284g++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)

Thanks,
Mit

**Comment by egorgrushin** [comment]
This solution works for me:
Logger.log({message: 'your message'});

**Comment by mitiaptest** [comment]
@GrushinEgor This is also works for me but without object only string not working.
